apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- mysql
- wordpress
namespace: lc2a-prod
secretGenerator:
- name: mysql-pass
  literals:
  - password=mysql_password
resources:
  - 00_namespace.yaml
  #- mysql-deployment.yaml
  #- wordpress-deployment.yaml
